import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import { convertTypeAcquisitionFromJson } from 'typescript'
import styles from '../styles/Home.module.css'

export default function Home() {

var array = ["monkey","cat","chihuahua"]

array.forEach((animal:string)=>{
  console.log(animal+"!")
})

//Stores counter in the state
const [counter, setcounter] = useState(1)
function incrementCounter(){
  setcounter((prevCounter)=>{
    return prevCounter + 1
  })
}
// Fetch GET Implementation
// // Gets Discord user details from Discord API
// async function getUser(discordId) {
// 	// API Endpoint
// 	const url = 'https://ellie-bot.fortnite.ca/api/pokemons/?ownerId=' + discordId;
// 	const response = await fetch(url, {
// 	  method: 'GET',
// 	  headers: {
// 		Accept: 'application/json',
// 	  },
// 	  redirect: 'follow',
// 	});
// 	if (response.ok) {
// 	  return await response.json();
// 	} else {
// 	  throw await response.json();
// 	}
//   }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={()=>incrementCounter()}>
      </button>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to PokéBot {counter}
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
